DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS faces;
DROP TABLE IF EXISTS unique_faces;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS job_status;